//! Author: Marceline Sorensen
//! Email: nadaso8th@gmail.com 
//! 
//! # about 
//! This module reads in a rust project, cleans up and validates a tokenstream generated by the rustc_lexer.

use rustc_lexer::*;
use std::{io::Read, path::Path};

struct FederScanner {
    project_folder: Path,
    
}